### ISSUE TITLE
Test intersectsCurve fails with TopologyException

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wfs20#125] opened 2018-08-16 12:58 UTC
SUT: http://cloudsdi.geo-solutions.it/geoserver/geoedge/ows?request=GetCapabilities&service=WFS
Version: 1.30-SNAPSHOT

The test IntersectsTests.intersectsCurve() fails three times with the same exception: `com.vividsolutions.jts.geom.TopologyException: side location conflict [ (18.2018, -67.0843, NaN) ]`

The failure occurs in https://github.com/opengeospatial/ets-wfs20/blob/22edc8f01a723fe0da53eecd0d786ce53c505264/src/main/java/org/opengis/cite/iso19142/basic/filter/spatial/IntersectsTests.java#L219-L220

**Comment by keshav-nangare** [comment] 2019-01-18 09:52
@lgoltz 

The service is changed so not able to reproduce this issue and also tried with other services as well but not reproducible.

**Comment by lgoltz** [comment] 2019-01-29 07:58
I'am able to reproduce the failure with the current master: 
[intersectsCurve650.html.txt](https://github.com/opengeospatial/ets-wfs20/files/2806560/intersectsCurve650.html.txt)

The docker environment contains only the WFS 2.0 ETS and was started with:
```
mvn clean install docker:run -Pdocker
```

**Comment by ghobona** [comment] 2020-07-14 06:36
@aaime Is the WFS mentioned in this Issue still available?

The endpoint does not appear to offer a WFS.

If the WFS is no longer available, we'll close the issue by 2020-07-21.

**Comment by aaime** [comment] 2020-07-14 07:14
@ghobona no we decommissioned that server some time ago. I do have locally a geodege database, but don't remember if it was subject to any license or redistribution restriction. Do you?

**Comment by ghobona** [comment] 2020-07-14 07:52
@aaime No, I am not familiar with geoedge's license or redistribution restrictions.

We'll close the issue. If the same problem comes up with a different server, we can reopen or link to this issue.

Thanks for the quick response.

**Closed** 2020-07-14 07:53 UTC
Labels: bug
