### ISSUE TITLE
Support for GML geometry types - Curve and Surface

### ISSUE THREAD

**Issue by carlospzurita** [opengeospatial/ets-wfs20#170] opened 2020-06-17 11:28 UTC
As a part of the validation process for WFS in the [INSPIRE validator](https://inspire.ec.europa.eu/validator/), there is a dependency from the TEAM engine for testing WFS 2.0 specification.

An user has opened an [issue](https://github.com/inspire-eu-validation/community/issues/314) in the community space for the validator sharing an error from the OGC testing engine with their service endpoint that you can find [here](http://192.71.92.21/MapService/wfs.axd/InspireTest?ACCEPTVERSIONS=2.0.0&REQUEST=GetCapabilities&SERVICE=WFS&VERSION=2.0.0). In specific, it is related to the spatial filters steps.

The features from the WFS use the geometries gml:Curve and gml:Surface. However, when performing  the tests for BBOX operator in Minimum Spatial Filter (from OGC ISO 19143: 7.8.3.2), this kind of geometries are not supported. Should these be valid in the TEAM engine?

Please, if this is not the appropriate place to post this issue, it would be very much appreciated if you could point to the correct one.

**Comment by dstenger** [comment] 2020-06-17 14:28
After having reviewed https://github.com/inspire-eu-validation/community/issues/314, the method causing the failure (`Extents.calculateEnvelope(geomNodes)`) seems to originate from geomatics-geotk dependency.

There might also be a relation to https://github.com/opengeospatial/ets-wfs20/issues/164.

@keshav-nangare Can you please take a closer look at this problem?

**Comment by keshav-nangare** [comment] 2020-06-20 05:59
@dstenger

I am able to reproduce the issue with the provided service and below are my findings:
1. The XPath is not resolved with prefix:namespace so it is failing to retrieve geom nodes from the provided service. So following are datafile and XPath for one of them feature type:
XPath: `//ns1:centrelineGeometry/*[1]`
Datafile: [RoadLink-4307837326955960477.xml.txt](https://github.com/opengeospatial/ets-wfs20/files/4807418/RoadLink-4307837326955960477.xml.txt)

Please find below code snippet for reference:
https://github.com/opengeospatial/ets-wfs20/blob/d64b2823482255709f2ac035c0bdaecff3376162/src/main/java/org/opengis/cite/iso19142/util/DataSampler.java#L367-L393

If we see above code snippet the XPath is built with `ns1` prefix and the element `centrelineGeometry` has prefix `net` in attached datafile. Due to that the above XPath is returning 0 geomNodes so method is returning null envelope. This leads to NullPointerException.

**Comment by calhanson** [comment] 2020-06-30 12:02
When I run the test, it successfully retrieves a geometry using XPath: `//ns1:centrelineGeometry/*[1]` after adding the namespace for the geometry element with `nsBindings.addNamespaceBinding(geomProp.getNamespace(), "ns1");` (as in code snippet above). Then `envelope = Extents.calculateEnvelope(geomNodes);` runs and throws an exception with message `Unssupported geometry type : [CurveType] id:geometry.RoadLink.SAMPLE_tn-ro_RoadLink_1`.

**Comment by keshav-nangare** [comment] 2020-06-30 18:05
@dstenger 

[1] http://192.71.92.21/MapService/wfs.axd/InspireTest?ACCEPTVERSIONS=2.0.0&REQUEST=GetCapabilities&SERVICE=WFS&VERSION=2.0.0

I tried with the provided service[1] but got the NullPointerException in spatial filter due that XPath, we can see the in below screenshot:
![Test_Session_Results_wfs20](https://user-images.githubusercontent.com/14732650/86161003-417db780-bb2a-11ea-9def-c6c187895bd4.png)

**Comment by ghobona** [comment] 2020-07-01 08:52
@carlospzurita the service appears to be down.

![Screenshot 2020-07-01 at 09 51 46](https://user-images.githubusercontent.com/18121038/86224209-7fa5c600-bb80-11ea-94ba-76107f2c82d4.png)

**Comment by calhanson** [comment] 2020-07-01 09:23
The service should now be up again.

@keshav-nangare The NullPointer test errors seem to be present in an altered version of the service, I also got this error when I ran the tests. Now the published service is updated with the unmodified version. Could you please run the test again, sorry for the inconvenience. Here is the response I get for the RoadLink feature type:
[RoadLink.xml.txt](https://github.com/opengeospatial/ets-wfs20/files/4856879/RoadLink.xml.txt)

**Comment by ghobona** [comment] 2020-07-08 08:39
@ghobona and @keshav-nangare discussed the issue on 2020-07-08.

Version of Geotoolkit used does not support Curve object.

@keshav-nangare will try passing the GML Curve object to a JTS MultiCurve.

**Comment by ghobona** [comment] 2020-07-15 08:43
@ghobona and @keshav-nangare discussed the issue on 2020-07-15.

@keshav-nangare to try passing the GML curve as a string to https://locationtech.github.io/jts/javadoc/org/locationtech/jts/io/gml2/GMLReader.html#read-java.lang.String-org.locationtech.jts.geom.GeometryFactory-

**Comment by ghobona** [comment] 2020-07-22 19:11
Sample GetFeature request http://192.71.92.21/MapService/wfs.axd/InspireTest?service=WFS&version=2.0.0&request=GetFeature&TypeNames=tn-ro:RoadLink

**Comment by keshav-nangare** [comment] 2020-07-29 10:14
The fix should be added in the [geomatics-geotk](https://github.com/opengeospatial/geomatics-geotk/) repository as the `Extents.calculateEnvelope(geomNodes)` method belonging to this repo.

Created the issue in `geomatics-geotk` repo: https://github.com/opengeospatial/geomatics-geotk/issues/3

**Comment by dstenger** [comment] 2020-09-14 08:33
Open task: Create pull request to update dependency geomatics-geotk to version 1.15.

**Closed** 2020-10-20 16:27 UTC
