### ISSUE TITLE
Direct WFS 2.0 Test - Spatial and Temporal Filter

### ISSUE THREAD

**Issue by Dnoack49** [opengeospatial/ets-wfs20#226] opened 2022-05-02 09:41 UTC
Dear community,

This issue includes the description of error-messages concerning the Spatial and Temporal Filter Conformance Classes.

**Temporal Filter**
While validating this [WFS](https://inspire.brandenburg.de/services/plu_bkt_jaenschwalde_wfs?service=WFS&version=2.0.0&request=GetCapabilities) (INSPIRE Annex Theme "Planned Land Use") using both, the _productive instance_ as well as the _staging instance_ we receive the following errors for the **Temporal Filter** conformance class

![grafik](https://user-images.githubusercontent.com/8046960/166209606-7b530a7e-bcc5-4c37-8343-8bed908d32ca.png)

According to the issue [NullPointerExceptions for several WFS tests #199](https://github.com/opengeospatial/ets-wfs20/issues/199) which described the same problem, the error has been fixed . As this is not the case for our implementation, we ask for adivce.

 
**Spatial Filter**
For the same WFS the test step '**invalid Geometry Operand**' results in an error when using the staging instance:
![grafik](https://user-images.githubusercontent.com/8046960/166212973-8b29e0fa-9d64-4116-9160-80cedd8654bd.png)

Yet, it does not when carrying out the test with the production instance (I think this should be correct, as the Featuretype OfficialDocumentation has no Geomety-Attribute):
![grafik](https://user-images.githubusercontent.com/8046960/166214033-bf2c126f-cdb4-45c5-964b-e8208abbc9c6.png)

Test reports:
[WFS-PLU-BKT_staginginstance.pdf](https://github.com/opengeospatial/ets-wfs20/files/8602037/WFS-PLU-BKT_staginginstance.pdf)
[WFS-PLU-BKT_productioninstance.pdf](https://github.com/opengeospatial/ets-wfs20/files/8602038/WFS-PLU-BKT_productioninstance.pdf)

Thank you.

**Comment by dstenger** [comment] 2022-05-02 12:53
Thank you for reporting.
Unfortunately, we currently cannot reproduce your problem as the provided service is not reachable.
Can you please bring the service back online so that we can check why the tests are failing?

**Comment by Dnoack49** [comment] 2022-05-02 13:44
Indeed we had an internal problem and the service was down. It is up again for you to check.

**Comment by dstenger** [comment] 2022-05-02 16:24
Regarding `Temporal Filter`, it seems that the same fix as implemented in https://github.com/opengeospatial/ets-wfs20/issues/199 has to be applied for test `before Period`.

Regarding `Spatial Filter`, following request
* POST https://inspire.brandenburg.de/services/plu_bkt_jaenschwalde_wfs
```
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs/2.0" count="10" service="WFS"
                version="2.0.0">
   <wfs:Query xmlns:ns39="http://inspire.ec.europa.eu/schemas/plu/4.0"
              typeNames="ns39:OfficialDocumentation"/>
</wfs:GetFeature>
```
returns a feature without geometry. This might be the root cause of the problem.

@bpross-52n Can you please take a closer look at the reported problems?

**Comment by mlcharv** [comment] 2022-09-12 11:46
Hi,
We think we ran into this problem when validating [this WFS](https://contenido.ign.es/wfs-inspire/unidades-administrativas?service=WFS&request=GetCapabilities), as explained in this issue:
INSPIRE-MIF/helpdesk-validator#831
Just wanted to check if any progress has been made 
Thank you!

**Comment by bpross-52n** [comment] 2022-10-12 13:42
Regarding Temporal Filter, this will be fixed with https://github.com/opengeospatial/ets-wfs20/pull/241

Regarding Spatial Filter, this will be fixed with https://github.com/opengeospatial/ets-wfs20/pull/237

**Closed** 2022-10-27 09:31 UTC
Labels: bug
