### ISSUE TITLE
ETS runs unpredictable tests and may cause unpredictable failures

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ets-wfs20#101] opened 2018-03-22 16:39 UTC
There is as small number of tests that are picking a random feature type to run tests on, instead of using them all, which can result in test passing one run, and failing in another.

![selezione_129](https://user-images.githubusercontent.com/325433/37784323-ca1537d4-2df7-11e8-879a-0e7cf046d096.png)

In the case of GeoServer that happens in "LockFeatureTests.lockSomeFeatures", but in general, other servers or other datasets could exhibit random behavior on the other tests too.

**Comment by aaime** [comment] 2018-03-22 16:55
Actually, here is what I think it's going on:
- The DataSampler class is created once per test session, collecting information about features at the very start
- The transaction/ReplaceTests replace one feature, changing its feature id
- The Lock test run after, picking a random feature type and a random feature, using the information collected by DataSampler

Given the WFS 1.1 test dataset I'm using is minimal (3 feature types, a handful of features), the likeliness of lock picking the feature type and feature type id of the replaced feature is small but not negligible. When that happens, the lockSomeFeature test fails.

**Comment by dstenger** [comment] 2018-03-26 11:39
Thank you for reporting. We will do further investigation.

**Comment by dstenger** [comment] 2018-03-26 11:47
The reported behaviour regarding lockSomeFeature test sounds like a bug (next, we will analyse the code).

Do you think we should minimize the random behaviour in general?

**Comment by aaime** [comment] 2018-03-26 12:11
@dstenger while having random behavior can be interesting from a hardening point of view, for a certification tool it's problematic. "Hey, it passed, I'm certified!" "No you're not, I tried and does not work!" "But I just tried again and it worked" (both being right). Hem....

**Comment by dstenger** [comment] 2018-03-26 12:17
I totally agree. We will consider this when implementing the fix.

**Comment by lgoltz** [comment] 2018-03-27 08:17
Usually all modifications on the test data caused by the transaction tests should be undone after execution of the test. This includes restoring of replaced of deleted features. This is done right after the tests, methods are annotated with `@AfterClass`, like in 

https://github.com/opengeospatial/ets-wfs20/blob/9151fcc1cbe2c50089707c7de6414af31708dcc3/src/main/java/org/opengis/cite/iso19142/transaction/ReplaceTests.java#L55-L57

But there may be changes which are not undone as described in #45  (issue is closed cause of low priority, but not fixed!). Furthermore #33 describes test failures of the test lockSomeFeatures and may be related.

I agree with you that random behaviour is unfavourable. Besides the already described problems it makes traceability of the tests more complicated. 
Using only one feature type (e.g. the first listed in the capabilities) is more transparent but a conclusion from one feature type to all feature types may not be sufficient for certification. 
So, the best approach is to test all feature types (and properties) which leads to a huge amount of requests.

**Comment by bermud** [comment] 2018-09-19 12:33
Maybe we can also provide as part of the input of the test information about feature(s) to be tested, or have a default behavior that picks the first feature type when sorted alphabetically to avoid the case that features listed in the GetCapabilities might be randomly sorted by the service.

**Comment by ghobona** [comment] 2020-07-31 11:50
@dstenger 

I support the suggestion in Comment https://github.com/opengeospatial/ets-wfs20/issues/101#issuecomment-422784869

Please create the relevant fix.

**Comment by dstenger** [comment] 2020-08-03 08:56
Discussed during CITE meeting on 2020-08-03:

We agreed on following solution: "have a default behavior that picks the first feature type when sorted alphabetically to avoid the case that features listed in the GetCapabilities might be randomly sorted by the service"

**Comment by keshav-nangare** [comment] 2020-08-12 08:33
@aaime 

Do we have demo service to reproduce the error?

**Comment by keshav-nangare** [comment] 2020-08-20 08:04
@dstenger @ghobona 

As I don't have service to reproduce the behavior. I have updated the `selectRandomFeatureType()` method so that it will pick the first feature type after sorted alphabetically according to the local name of feature types. I tried to test the changes by deploying Geoserver but getting some issues.

Please find the changes in #173 PR.

**Comment by aaime** [comment] 2020-08-20 08:08
Ah hey, sorry for late answers, vacations plus deathmarching on the TB16 DGGS thread kept me from following up on other topics.

If you want a deployed GeoServer, you can use the TB16 one: https://tb16.geo-solutions.it/geoserver/
Warning: it has a lots of feature types, and some really big.

**Comment by ghobona** [comment] 2020-08-25 11:01
@keshav-nangare Please install a local copy of geoserver to test with.

**Comment by dstenger** [comment] 2020-09-02 08:23
PR #173 applies changes which pick the first feature type instead of a random feature type.

However, @keshav-nangare can you please check if a random feature or the first feature is picked?

This, does not solve the problem reported in this issue directly but just removes then random-mechanism.
I think the root cause of this issue is that changes made by transaction-tests might not be undone completely so that a replaced feature is locked in a further test which is failing then, obviously.

**Comment by keshav-nangare** [comment] 2020-09-16 08:03
Following are the current workflow of the ReplaceTest and findings:

  1. Replace test uses the featureType from datasampler and retreives the feature by making http request. but it 
  2. The replacement tests creates new temp elment to perform the replace test operation on feature without changing the original feature list from the data sampler.
  3. The replacement copy is used to replace feature and original copy is saved to restored after Replace test execution.
  4. The request is made using replacement copy gives the response as it is replacement of one feature is happened. 
  5. If we try to aquire lock feature on same feature it will return lock because that feature is restored before the locaking test.

**Comment by dstenger** [comment] 2020-09-16 08:40
As far as we see, the replace tests do not affect the lock tests. So, we do not see any further actions for this issue and will close it by merging #173.

If any further problem pops up regarding the replace and lock tests, please create a new issue.

**Closed** 2020-10-09 18:08 UTC
Labels: bug
