### ISSUE TITLE
WFS 2.0 - invalid GeometryOperand Unexpected HTTP status code

### ISSUE THREAD

**Issue by CeciliaPH** [opengeospatial/ets-wfs20#275] opened 2024-06-11 14:04 UTC
**Describe the bug**
We are validating our services against your validator and we are getting some errors like:
org.opengis.cite.iso19142.basic.filter.spatial.BBOXTests
invalidGeometryoperand
OGC TEAM Engine reported a failed test: Unexpected HTTP status code.

**To Reproduce**
We checked our service:
 https://www.ign.es/wfs-inspire/unidades-administrativas?request=GetCapabilities&service=WFS

**Expected behavior**
We would need an specific response or explanation for this error to try to guess a solution.

**Additional context**
We are not sure if this is the same issue as https://github.com/opengeospatial/ets-wfs20/issues/247

**Comment by dstenger** [comment] 2024-06-12 16:36
Thank you for reporting.

I can reproduce the behavior and, indeed, the logged request in HTML report returns HTTP status code 403 which is valid for this test.
We will do further investigation.

**Comment by bpross-52n** [comment] 2024-09-05 08:56
Thanks, @dstenger. As we discussed internally, I tested with Postman and I get a HTTP 200 response with feature data. Looking at the log, it seems that the Test Suite also receives a HTTP 200 response. The test expects either a HTTP 400 or 403 response. 
We will update the error message with the actual HTTP response code for a better understanding.

**Comment by bpross-52n** [comment] 2024-09-19 08:45
We enhanced the error message (will be installed on the beta test engine soon: https://cite.ogc.org/te2/). Now, when I test your service, it will report `Unexpected HTTP status code. Expected '400' or '403', was '200'`. Can you please check why your service responds with a 200 for the request below?

> Thank you for reporting.
> 
> I can reproduce the behavior and, indeed, the logged request in HTML report returns HTTP status code 403 which is valid for this test. We will do further investigation.
> 
> Workflow of reproducing HTTP Status 403 (using Firefox plugin RESTED):
> 
> * POST https://contenido.ign.es/wfs-inspire/unidades-administrativas
> 
> ```
> <wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs/2.0" count="10" service="WFS"
>                 version="2.0.0">
>    <wfs:Query xmlns:ns84="http://inspire.ec.europa.eu/schemas/au/4.0"
>               typeNames="ns84:AdministrativeUnit">
>       <fes:Filter xmlns:fes="http://www.opengis.net/fes/2.0">
>          <fes:BBOX>
>             <fes:ValueReference xmlns:tns="http://www.opengis.net/gml/3.2">tns:description</fes:ValueReference>
>             <gml:Envelope xmlns:gml="http://www.opengis.net/gml/3.2" srsName="urn:ogc:def:crs:EPSG::4258">
>                <gml:lowerCorner>27.62 -18.17</gml:lowerCorner>
>                <gml:upperCorner>43.8 4.33</gml:upperCorner>
>             </gml:Envelope>
>          </fes:BBOX>
>       </fes:Filter>
>    </wfs:Query>
> </wfs:GetFeature>
> ```
> 
> However, the response body is empty which would also lead to a failing test.
> 
> Thus, it might be that the response originates from a proxy server and not the application itself.

**Closed** 2024-09-23 13:10 UTC
Labels: enhancement

**Comment by CeciliaPH** [comment] 2024-10-29 14:43
Dear all,

I am not sure if this issue is solved. I tried another service and I am experiencing the same error.
However, if I post the  saved request in a post request (outside of the validator), I got the right information, the 10 first features of the service.
https://www.ign.es/wfs-inspire/ngbe?request=GetCapabilities&service=WFS

If you look at the last line of the output it is cut. The URL is not completed. Is this normal?

I am really interested in solving this issues and pass the validation but don't get the clue of what the errors are or how to solve them.

Cecilia
____

invalid Geometry Operand
Class Name:BBOXTests
Method Name:invalidGeometryOperand
Path:org/opengis/cite/iso19142/basic/filter/spatial/BBOXTests

Method:	POST
URL:	https://contenido.ign.es/wfs-inspire/ngbe

<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs/2.0" count="10" service="WFS"
                version="2.0.0">
   <wfs:Query xmlns:ns76="http://inspire.ec.europa.eu/schemas/gn/4.0"
              typeNames="ns76:NamedPlace">
      <fes:Filter xmlns:fes="http://www.opengis.net/fes/2.0">
         <fes:BBOX>
            <fes:ValueReference xmlns:tns="http://www.opengis.net/gml/3.2">tns:description</fes:ValueReference>
            <gml:Envelope xmlns:gml="http://www.opengis.net/gml/3.2" srsName="urn:ogc:def:crs:EPSG::4258">
               <gml:lowerCorner>27.17 -18.17</gml:lowerCorner>
               <gml:upperCorner>43.86 4.33</gml:upperCorner>
            </gml:Envelope>
         </fes:BBOX>
      </fes:Filter>
   </wfs:Query>
</wfs:GetFeature>


**Outputs:**
<cnt:rest><wfs:FeatureCollection xmlns:wfs="http://www.opengis.net/wfs/2.0"
                       xmlns:gml="http://www.opengis.net/gml/3.2"
                       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       numberMatched="10"
                       numberReturned="10"
                       timeStamp="2024-10-29T14:34:21Z"
                       xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd http://inspire.ec.europa.eu/schemas/gn/4.0 https://contenido.ign.es/wfs-inspire/ngbe?SERVICE=WFS&amp;VERSION=2.0.0&amp;REQUEST=DescribeFeatureType&amp;OUTPUTFORMAT=application%2Fgml%2Bxml%3B+version%3D3.2&amp;TYPENAME=gn:NamedPlace&amp;NAMESPACES=xmlns(gn,http%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Fgn%2F4.0)">
  <wfs:boundedBy>
      <gml:Envelope srsName="http://www.opengis.net/def/crs/EPSG/0/4258">
         <gml:lowerCorner>36.620300 -5.578979</gml:lowerCorner>
         <gml:upperCorner>41.832520 0.539124</gml:upperCorner>
      </gml:Envelope>
  </wfs:boundedBy>
  <wfs:member>
      <gn:NamedPlace xmlns:gn="http://inspire.ec.europa.eu/schemas/gn/4.0"
                     gml:id="ES.IGN.NGBE.2394220">
         <gn:beginLifespanVersion>2024-03-21T00:00:00</gn:beginLifespanVersion>
         <gn:endLifespanVersion nilReason="other:unpopulated" xsi:nil="true"/>
         <gn:geometry>
        
        <gml:Point gml:id="ES.IGN.NGBE.2394220_GN_GEOMETRY"
                       srsName="http://www.opengis.net/def/crs/EPSG/0/4258">
               <gml:pos>37.333131 -3.522705</gml:pos>
            </gml:Point>
         </gn:geometry>
         <gn:inspireId>
            <base:Identifier xmlns:base="http://inspire.ec.europa.eu/schemas/base/3.3">
               <base:localId>2394220</base:localId>
               <base:namespace>ES.IGN.NGBE</base:namespace>
            </base:Identifier>
         </gn:inspireId>
         <gn:leastDetailedViewingResolution nilReason="other:unpopulated" xsi:nil="true"/>
         <gn:localType>
            <gmd:LocalisedCharacterString xmlns:gmd="http://www.isotc211.org/2005/gmd" locale="es-ES">Montaña</gmd:LocalisedCharacterString>
         </gn:localType>
         <gn:mostDetailedViewingResolution nilReason="other:unpopulated" xsi:nil="true"/>
         <gn:name>
            <gn:GeographicalName>
               <gn:language>spa</gn:language>
               <gn:nativeness xmlns:xlink="http://www.w3.org/1999/xlink"
                              xlink:href="https://inspire.ec.europa.eu/codelist/NativenessValue/endonym"/>
               <gn:nameStatus xmlns:xlink="http://www.w3.org/1999/xlink"
                              xlink:href="http://inspire.ec.europa.eu/codelist/NameStatusValue/other"/>
               <gn:sourceOfName>MITMA.IGN.BTN25</gn:sourceOfName>
               <gn:pronunciation nilReason="other:unpopulated" xsi:nil="true"/>
               <gn:spelling>
                  <gn:SpellingOfName>
                     <gn:text>Peñón del Asno</gn:text>
                     <gn:script>Latn</gn:script>
                  </gn:SpellingOfName>
               </gn:spelling>
            </gn:GeographicalName>
         </gn:name>
         <gn:relatedSpatialObject nilReason="other:unpopulated" xsi:nil="true"/>
         <gn:type xmlns:xlink="http://www.w3.org/1999/xlink"
                  xlink:href="http://inspire.ec.europa.eu/codelist/NamedPlaceTypeValue/landform"/>
      </gn:NamedPlace>
  </wfs:member>
  <wfs:member>
      <gn:NamedPlace xmlns:gn="http://inspire.ec.europa.eu/schemas/gn/4.0"
                     gml:id="ES.IGN.NGBE.4038379">
         <gn:beginLifespanVersion>2024-03-21T00:00:00</gn:beginLifespanVersion>
         <gn:endLifespanVersion nilReason="other:unpopulated" xsi:nil="true"/>
         <gn:geometry>
        
        <gml:Point gml:id="ES.IGN.NGBE.4038379_GN_GEOMETRY"
                       srsNa**me="http://www.opengis.net/def/crs/EPSG/0/425</cnt:rest>**

**Comment by dstenger** [comment] 2024-10-29 15:29
Hello @CeciliaPH,

We created a pull request which is currently installed on [Beta environment](https://cite.ogc.org/te2/) (not yet on [Production environment](https://cite.ogc.org/teamengine/)).

However, the pull request only contains an updated error message.
It seems that your service is not responding correctly as documented in https://github.com/opengeospatial/ets-wfs20/issues/275#issuecomment-2360389527.
The test expects HTTP status code 400 or 403 but your service responds with HTTP status code 200.

**Comment by CeciliaPH** [comment] 2024-10-29 16:06
Thanks so much for the answer... and sorry because previously I didn't understand it was in beta environment.
I could re-run the test and now the error is more explicit, so that regarding to the test is ok.
I am reading the comment in 
https://github.com/opengeospatial/ets-wfs20/issues/275#issuecomment-2360389527.
and certainly I also didn't understand the comment. Re-reading again.. If the request is valid, why it should return a 400 or 403 code? 
The bbox in the request is correct, inside the limits of the WFS, and I assume that is why it returns some results (200). Which is the invalid operand you are testing?

Thanks again for your comments.

**Comment by dstenger** [comment] 2024-10-29 16:16
The JavaDoc describes what is tested:
https://github.com/opengeospatial/ets-wfs20/blob/aee1fbe0693d7198647fd18b9c1aea72dd9fa2f7/src/main/java/org/opengis/cite/iso19142/basic/filter/spatial/BBOXTests.java#L216-L228

So, a BBOX is used with a property which does not contain a geometry (tns:description in your case). This is not a valid request which should lead to a HTTP status code 400 or 403 in the response.

**Comment by CeciliaPH** [comment] 2024-10-29 16:20
Thanks again. I am afraid this is something from the server software, (deegree) and not sure if we will be able to fix it. We will try to fight a bit and see if we can get something. 
I hope I can come later with better news.

**Comment by dstenger** [comment] 2024-10-29 16:23
You are welcome to create an issue in the deegree issue tracker if the problem is software related: https://github.com/deegree/deegree3/
One of the reference implementations also uses deegree and does not have the problem (maybe, the configuration is different there): https://cite.deegree.org/deegree-webservices-3.5.6/services/wfs200?service=WFS&request=GetCapabilities
